name: Build CLI - Ubuntu

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run package
      - run: cp $(command -v node) filebase
      - run: yarn run inject
      - uses: actions/upload-artifact@v4
        with:
          name: filebase
          path: filebase

