name: Build CLI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 21
        os:
          - linux
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run package
      - run: cp $(command -v node) filebase
      - run: npx postject filebase NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
      - uses: actions/upload-artifact@v4
        with:
          name: filebase_${{matrix.os}}-${{ matrix.arch }}
          path: filebase

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 21
        os:
          - macos
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run package
      - run: cp $(command -v node) filebase
      - run: codesign --remove-signature filebase
      - run: npx postject filebase NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
      - run: codesign --sign - filebase
      - uses: actions/upload-artifact@v4
        with:
          name: filebase_${{matrix.os}}-${{ matrix.arch }}
          path: filebase

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 21
        os:
          - win
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run package
      - run: node -e "require('fs').copyFileSync(process.execPath, 'filebase.exe')"
      - run: signtool remove /s filebase.exe
      - run: npx postject filebase.exe NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
      - uses: actions/upload-artifact@v4
        with:
          name: filebase_${{matrix.os}}-${{ matrix.arch }}
          path: filebase.exe

